FROM nginx:1.30.4-trixie

COPY . /usr/share/nginx/html/

# Documenta el puerto 80 del contenedor
EXPOSE 80

# Este es el comando por defecto que ejecuta el contenedor
# CMD ["nginx", "-g", "daemon off;"]